package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.junit.Test;

public class DeletTest extends TestBase {

  @Test
  public void deletGroups() {
    gotoGroupPage();
    selectGroup();
    deleteSelectedGroups();
    returnToGroupPage();
  }

}
