package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.junit.Test;

public class TestAddressbookTest extends TestBase {

  @Test
  public void testAddressbook() {

    gotoGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("testGroup5", "Name1", "LastName1"));
    submitGroupCreation();
    returnToGroupPage();

  }

}
