package ru.stqa.pft.addressbook.test;// Generated by Selenium IDE

import org.junit.Test;

public class DeletTest extends TestBase {

  @Test
  public void deletGroups() {
    app.getNavigationHelper().gotoGroupPage();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }

}
