package ru.stqa.pft.addressbook.test;// Generated by Selenium IDE

import org.junit.Test;
import ru.stqa.pft.addressbook.model.GroupData;

public class TestAddressbookTest extends TestBase {

  @Test
  public void testAddressbook() {

    app.getNavigationHelper().gotoGroupPage();
    app.getGroupHelper().initGroupCreation();
    app.getGroupHelper().fillGroupForm(new GroupData("testGroup5", "Name1", "LastName1"));
    app.getGroupHelper().submitGroupCreation();
    app.getGroupHelper().returnToGroupPage();

  }

}
